---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mercadom/public_html/oruidoscomputadores.pt/api/
    - rsync -av --exclude='.env' --exclude='.git' --exclude='storage/app' --exclude='storage/logs' ./ $DEPLOYPATH
    - /usr/local/bin/php -r "if (!file_exists('{$DEPLOYPATH}.env')) { echo 'AVISO: .env em falta em produção, criar manualmente.'; }"
